apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  claimRef:
    namespace: default
    name: pvc-nfs
  nfs:
    server: 172.28.251.39
    path: "/srv/nfs/laramysql/"
  persistentVolumeReclaimPolicy: Retain